name: .NET Framework Build and C# Code Check

on:
  push:
    branches:
      - new_vetochkaa
  pull_request:
    branches:
      - new_vetochkaa

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Framework Developer Pack
        run: choco install netfx-4.7.2-devpack -y

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Format C# code only
        run: dotnet format ./IS_Bibl.sln --verify-no-changes

      - name: Check for changes after formatting
        run: git diff --exit-code
