name: XAML Syntax Check

on:
  push:
    branches:
      - new_vetochkaa
  pull_request:
    branches:
      - new_vetochkaa

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install XAML Styler
      run: dotnet tool install -g XamlStyler.Console

    - name: Format XAML files
      run: xstyler -d ./IS_Bibl/

    - name: Check for changes after formatting
      run: git diff --exit-code
